---
- hosts: ci

  vars:
    tomcat_home: '/home/tomcat8'
    jenkins_home: '{{tomcat_home}}/jenkins'
    jenkins_war: '{{tomcat_home}}/jenkins.war'

  handlers:
    - name: restart tomcat8
      service: name=tomcat8 state=restarted

  tasks:
    - name: installation de Git
      package: name=git state=present

    - name: installation de Maven
      package: name=maven state=present

    - name: installation du jdk8
      package: name=openjdk-8-jdk-headless state=present

    - name: création compte pour Tomcat8
      user: name=tomcat8 shell=/bin/false system=yes home='{{tomcat_home}}'

    - name: installation de Tomcat 8
      package: name=tomcat8 state=present

    - name: création des répertoires pour jenkins
      file:
        path: '{{jenkins_home}}'
        state: directory
        owner: tomcat8
        group: tomcat8

    - name: configuration du répertoire pour jenkins
      lineinfile:
        name: '/etc/default/tomcat8'
        line: 'JENKINS_HOME={{jenkins_home}}'
      notify:
        - restart tomcat8

    - name: installation de jenkins
      get_url:
        url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
        dest: '{{jenkins_war}}'
        group: tomcat8
        owner: tomcat8

    - name: copie du fichier de déploiement pour Jenkins
      template:
        src: jenkins-context.xml
        dest: /var/lib/tomcat8/conf/Catalina/localhost/jenkins.xml
        owner: tomcat8
        group: tomcat8
      notify:
        - restart tomcat8
