- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: creation du compte pour TomEE
  user:
    name: tomee
    shell: /bin/false
    system: yes
    home: '{{tomee_home}}'

- name: telechargement de l'archive TomEE
  get_url:
    url: '{{tomee_url}}'
    dest: '/tmp/{{tomee_archive}}'

- name: installation de TomEE
  unarchive:
    src: '/tmp/{{tomee_archive}}'
    dest: '{{tomee_dest}}'
    creates: '{{tomee_home}}/bin/startup.sh'
    copy: no
    group: tomee
    owner: tomee

- name: copie du fichier unit Systemd pour TomEE
  template:
    src: 'roles/tomee-server/templates/tomee.service'
    dest: '/etc/systemd/system/tomee.service'
  notify:
    - recharger daemon
    - redemarrer TomEE

